---
title: "Paper 3 results"
output: html_notebook
---

In order to determine the number and composition of the orientations concept, we run a series of **Exploratory and Confirmatory Factor Analysis, as well as ICLUST analysis on the values variables.** 


```{r setup, echo=FALSE, warning=FALSE, message=FALSE, results='hide'}

#========================
#GETTING THE SURVEY DATA 
#========================

bots<- read_csv("~/Dropbox/1PhD/Articles/Survey Data/bots_renamed.csv") 

createdata <- function(x) {
  bots %>%
    dplyr::select(grep(x, names(bots)))
}

corstars <-function(x, method=c("pearson", "spearman"), removeTriangle=c("upper", "lower"),
                    result=c("none", "html", "latex")){
 
   #Compute correlation matrix
  require(Hmisc)
  x <- as.matrix(x)
  correlation_matrix<-rcorr(x, type=method[1])
  R <- correlation_matrix$r # Matrix of correlation coeficients
  p <- correlation_matrix$P # Matrix of p-value 
  
  ## Define notions for significance levels; spacing is important.
  mystars <- ifelse(p < .0001, "****", ifelse(p < .001, "*** ", ifelse(p < .01, "**  ", ifelse(p < .05, "*   ", "    "))))
  
  ## trunctuate the correlation matrix to two decimal
  R <- format(round(cbind(rep(-1.11, ncol(x)), R), 2))[,-1]
  
  ## build a new matrix that includes the correlations with their apropriate stars
  Rnew <- matrix(paste(R, mystars, sep=""), ncol=ncol(x))
  diag(Rnew) <- paste(diag(R), " ", sep="")
  rownames(Rnew) <- colnames(x)
  colnames(Rnew) <- paste(colnames(x), "", sep="")
  
  ## remove upper triangle of correlation matrix
  if(removeTriangle[1]=="upper"){
    Rnew <- as.matrix(Rnew)
    Rnew[upper.tri(Rnew, diag = TRUE)] <- ""
    Rnew <- as.data.frame(Rnew)
  }
  
  ## remove lower triangle of correlation matrix
  else if(removeTriangle[1]=="lower"){
    Rnew <- as.matrix(Rnew)
    Rnew[lower.tri(Rnew, diag = TRUE)] <- ""
    Rnew <- as.data.frame(Rnew)
  }
  
  ## remove last column and return the correlation matrix
  Rnew <- cbind(Rnew[1:length(Rnew)-1])
  if (result[1]=="none") return(Rnew)
  else{
    if(result[1]=="html") print(xtable(Rnew), type="html")
    else print(xtable(Rnew), type="latex") 
  }
} 
```

```{r correlation matrix items, warning=FALSE, echo=FALSE, message=FALSE, results='hide',fig.keep='all'}
#Make a data frame that only includes data for values variables
values <- bots[,grepl("values", names(bots))]

#After the examination, we took out the market value data, since they were highly skewed. 
values <- values[,!grepl("Market", names(values))] 

#Correlation matrix (lower part)
knitr::kable(corstars(values), booktabs = TRUE, 
  caption = "Correlation table, all items."
)

```


```{r findingfactors, warning=FALSE, echo=FALSE}
#Finding the number of factors
par <- fa.parallel(values) #analysis suggests 3 factors 
```

```{r EFA graph, warning=FALSE, echo=FALSE, message=FALSE, results='hide',fig.keep='all'}
#CFA using the psych package
test.simple <- fa(r=cor(values, use="complete.obs"), nfactors=3, fm="ml", rotate="oblimin")
fa.diagram(test.simple, cut = .4, digits = 2)
```


These are the Gris (2001) validity scores: 
```{r valid, echo=F, warning=F}
print(as.data.frame(test.simple$valid, row.names = c("ML1", "ML2", "ML3")))
```



```{r iclust2, echo=F, warning=F, message=FALSE, results='hide',fig.keep='all'}
fa.diagram(ICLUST(values,2,title="Two cluster solution"),main="Input from ICLUST")
```


```{r omega, echo=FALSE, warning=FALSE, message=FALSE, results='hide',fig.keep='all'}
omega(values)
```


```{r alpha, echo=FALSE, warning=FALSE}
keys.list <- list(creative=c(6,7,4,8,3,5,2), entrepreneurial=c(15,14,13,1), 
                   financial=c(11,10,16,12,9))

myKeys <- make.keys(values,keys.list)
my.scores <- scoreItems(myKeys,values) #form several scales
print(as.data.frame(rbind(my.scores$alpha, my.scores$G6)))
```








